arrowParens: always
bracketSpacing: true
endOfLine: auto
printWidth: 120
proseWrap: preserve
quoteProps: as-needed
semi: true
singleQuote: false
tabWidth: 2
trailingComma: all
useTabs: false
overrides:
  - files: "*.sol"
    options:
      printWidth: 120
      tabWidth: 4
      useTabs: false

